# Generated by Django 2.0.1 on 2018-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nacimento'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nacimento'),
        ),
    ]
