# Generated by Django 2.0.1 on 2018-01-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180126_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor corrida')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Motorista')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Passageiro')),
            ],
        ),
    ]
